### PR TITLE
CF-2986 | Remove 'Duel with' option from player menu if member_world …

### PR DESCRIPTION
**Pull request by aldrichdev**
…is false (F2P)

Potential fix for [#2986](https://gitlab.com/open-runescape-classic/core/-/issues/2986). This is my first change to the ORSC codebase, so please review carefully.

### CODE REVIEW

**Comment by 15rtrujillo** [comment]
LGTM

**Comment by aldrichdev** [comment]
> LGTM, however it would probably be wise to also block dueling in F2P server side. Doesn't look like that's currently implemented, but I could be looking in the wrong place. And this could be done later, of course.

Good point. I'm not sure how to do that

**Comment by lmsv-mx123** [comment]
So the file you want to look at is https://gitlab.com/open-runescape-classic/core/-/blob/develop/server/src/com/openrsc/server/net/rsc/handlers/PlayerDuelHandler.java at the method handlePacket(). Basically you would want to include if (!player.getWorld().getServer().getConfig().MEMBER_WORLD) { return; } - in the if probably could be convenient call to `unsetOptions`, I see that sometimes gets placed

**Comment by aldrichdev** [comment]
@15rtrujillo @lmsv-mx123 PR is updated, logic should be prevented. Teste this locally with 2 accounts and member_world: false, if they both select "Duel with" nothing happens. However with member_world: true, it works as expected.

**Comment by lmsv-mx123** [comment]
LGTM

**Pull request merged**
