### PR TITLE
Implemented ::setcurstat Admin Command

### PR DESCRIPTION
**Pull request by KeplerIO**
This PR aims to resolve open issue #1527

Usage - ::setcurstat [player] [skill_id] [level]

This allows an admin to set the current effective level of any stat for any player including him/her self.

Command cancelled if the player is not found within the world at time of execution.

Command is cancelled if the admin tries to modify an invalid/non-existent skill.

EDIT: As per Kenix, this should also take the skill as a string and not just the skill ID... That behavior is not currently supported with this code.

### CODE REVIEW

**Comment by Marwolf** [comment]
screen shot 2019-01-27 at 18 44 00

Def need to change from skill ID to skill name like in the ::setstat command

Also the setstat command now is ::setstat marwolf 99 attack

The 99 and attack are reversed from where they were before. Would need to follow that pattern with ::setcurstat

**Comment by Marwolf** [comment]
Kenix writes:
Step 1: Copy ::setstat
Step 2: Change player.getSkills().setLevelTo() to player.getSkills().setLevel()

**Comment by KeplerIO** [comment]
Ok understood. Will do this.

**Comment by KeplerIO** [comment]
Making necessary changes now. Apologies all. I'll do better in future to make mindful effort to not put myself or project in this position.

**Review by Kenix3 — APPROVED** [review]
Looks good this time. Thanks for following command conventions.

**Pull request merged**
