### PR TITLE
Center Login Screen

### PR DESCRIPTION
**Pull request by kInGkRiStOf**
Reset all the spacing to center the login and new user portions of the login screen. Also reset the pictures that come up, for use in full screen. Will need to adjust them later on, along with issues I posted in github.

### CODE REVIEW

**Comment by kInGkRiStOf** [comment]
continuing issues:

The blue bar at the bottom of the screen does not stretch across the entire screen when enlarged. Unable to locate it in the code. It is the same bar is in game, with the "all messages" at the bottom, which is located at:
mudclient.java drawChatMessageTabs()

The objects in view 2 and 3 of the pictures are not loading. They should be loaded in:
world.java addLoginScreenModels()
and addLoginScreenModels() gets called in:
mudclient.java renderLoginScreenViewports()

**Comment by kInGkRiStOf** [comment]
Blue Bar: I tried to search by space(the blue bar should be 512 width, which is the original space; by color(look up every color in the classes); by variables set to both of those; by related things, no luck.

Objects in pictures: I attempted setting values at much higher, and lower values, and nothing else loaded; I tried to do the math to figure out their sectors, and the x,y of those sectors, and couldn't get them to load still. However, I was able to double, or quadruple the objects in game in the first picture(lumby).

**Comment by kInGkRiStOf** [comment]
Blue bar resizing fixed. Chris showed me it was a sprite, so i just made it cover the entire screen.

Attempted to put the screen rendering into reposition(), and it crashes the game upon resizing of screen, will leave it in update() unless chris can find a fix.

**Review by Christofosho — COMMENTED** [review]
Code looks good.

**Pull request closed without merging**
